global:
  #Inject config maps
  inject_maps: []

  routing:
    type:

  operator:
    keycloak:
      realm:
  db:
    port:
    host:

  # node selector for the pods
  nodeSelector:
  
  # tolerations for the pods
  tolerations:


# Name of the instance, default {{ .Release.Name }}-{{ .Values.name | default .Chart.Name }}
name:

# Application image
image:
  # Docker registry
  registry: "ghcr.io"
  # Docker repository (application name)
  repository: "change-me"
  # Docker image tag (application version)
  tag: "main"
  # pull policy Always | IfNotPresent | Never
  pull: IfNotPresent

# Image pull secrets
imagePullSecrets:

# health
livenessProbe:
  url: /q/health/live

readinessProbe:
  url: /q/health/ready

startupProbe:
  url: /q/health/started

# Template env variable for Quarkus application
template:
  db_property_url: "_PROD_QUARKUS_DATASOURCE_JDBC_URL"
  db_property_username: "_PROD_QUARKUS_DATASOURCE_USERNAME"
  db_property_password: "_PROD_QUARKUS_DATASOURCE_PASSWORD"

# node selector for the pods
nodeSelector:

# tolerations for the pods
tolerations:

# pod
pod:
  port: 8080

# service
service:
  port: 8080

# Routing
routing:
  # Enable or disable routing
  enabled: false
  # Default URL
  default_url: "change.com"

  # traefik | ingress
  type: none

  # path
  path:

  # routing for bff
  bff: false

  # host configuration
  host:
    # prio1 if the name is define generate domain <override>.<default_url>
    override:
    # prio2 if the name is define generate domain <name>-<release_namespace>.<default_url>
    name:
    # else <release_name>-<name of chart_name>-<release_namespace>.<default_url>

  traefik:
    # middleware
    middleware:
      # middleware for treafik
      enabled: false
      # traefik middleware name
      name: 

  # ingress
  ingress:
    annotations:
      ingress.kubernetes.io/ssl-redirect: "false"

  # custom service name and port for the routing
  service:
    name:
    port:

# Replicas
replicas: 1


serviceAccount:
  enabled: false
  name: 

# Deprecated: Service account suffix
serviceAccountSuffix:

# Inject config maps
inject_maps: []

# Database configuration
db:
  # Enable or disable database connection
  enabled: false

  # Database name
  database:

  # Database username
  username:

  # Database password
  password:

  # Database port
  port: 5432

  # enable or disable database operator to create a schema for the application
  operator: true

  # JDBC url. Generated
  # url: "jdbc:postgresql://localhost:5432/changeit"

  # Database host, Generated
  # host: app-postgresql

  # Database image
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: 12.2.0

# Kubernetes operator configuration
operator:
  # permissions
  permission:
    # enable or disable configuration for operator
    enabled: false

    spec:      
      # default deployment name (release_name-name)
      appId:
      # application name (release_name-name)
      name:
      # application description (release_name-name)
      description:
      # map of permissions
      # resource:
      #    action: description
      permissions:

  # Data mgmt operator
  data:
    mgmt:
      # enabled or disable config for operator
      enabled: true
      # database type POSTGRES
      dbType: POSTGRES
      # file prefix for the scenario
      prefix:
      # schema
      schema: public

  # Keycloak operator
  keycloak:
    # enabled or disable config for operator
    enabled: false
    # keycloak realm
    realm: master
    # path to the client JSON file
    client:
    # path to the roles JSON file
    roles:
    # path to the realms JSON file
    realms:

  # microfrontend
  microfrontend:
    # enable or disable configuration for operator
    enabled: false
    # default remote entry path suffix
    entrySuffix: remoteEntry.js

    # definnition
    spec:
      description: change-me
      exposedModule: change-me
      iconName:
      note: change-me
      remoteName:
      tagName:      
      # list of strings
      classifications: []      
      # list of name and path
      # - name:
      #   path:
      endpoints:
      # technology is free text
      technology: ANGULAR
      # contact email
      contact: onecx@1000kit.org
      # default is app.routing.path
      remoteBaseUrl:
      # default is app.routing.path + entrySuffix
      remoteEntry:
      # default release name (product name)
      productName:      
      # default deployment name (release_name-name or appId)
      appId:
      # default deployment name (release_name-name)
      appName:
