{{ if .Values.db.enabled }}
{{ if .Values.operator.data.mgmt.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "app.fullname" $ }}-data-mgmt-config"
  labels:
    app: {{ template "app.fullname" $ }}
{{ include "app.labels.common" $ | indent 4 }}
data:
  datasource-config: |-
    {
      "fileNamePrefix": "{{ .Values.operator.data.mgmt.prefix | default (include "app.fullname" $) }}",
      "dbType": "{{ .Values.operator.data.mgmt.dbType }}",
      "url": {{ include "app.db.url" $ }},
      "user": "{{ include "app.db.username" $ }}",
      "password": "{{ include "app.db.password" $ }}",
      "dbSchemeName": "{{ .Values.operator.data.mgmt.schema }}"
    }
{{ end }}
{{ end }}
