{{ if .Values.operator.apm.enabled }}
{{ if .Values.operator.apm.permissions }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "quarkus.fullname" $ }}-apm-config"
  annotations:
    appId: {{ template "quarkus.fullname" $ }}
    filename: "permissions.csv"
  labels:
    app: {{ template "quarkus.fullname" $ }}
{{ include "quarkus.labels.common" $ | indent 4 }}
data:
  permissions.csv: |-
{{ $.Files.Get .Values.operator.apm.permissions | indent 4 }}
{{ end }}
{{ end }}
