{{ if .Values.operator.keycloak.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "quarkus.fullname" $ }}-kc-config"
  annotations:
    tkit.kc.cli/target-realm: {{ .Values.global.operator.keycloak.realm | default .Values.operator.keycloak.realm }}
  labels:
    app: {{ template "quarkus.fullname" $ }}
{{ include "quarkus.labels.common" $ | indent 4 }}
data:
{{ if .Values.operator.keycloak.client }}
  client: |-
{{ tpl ( $.Files.Get .Values.operator.keycloak.client ) . | indent 4 }}  
{{- end }}
{{ if .Values.operator.keycloak.roles }}
  roles: |-
{{ tpl ( $.Files.Get .Values.operator.keycloak.roles ) . | indent 4 }}
{{- end }}
{{ if .Values.operator.keycloak.realms }}
  realms: |-
{{ tpl ( $.Files.Get .Values.operator.keycloak.realms ) . | indent 4 }}  
{{- end }}
{{- end }}
