{{- if .Values.routing.enabled }}
{{- if eq (include "quarkus.routing.type" $) "ingress" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  {{ .Release.Name }}-ingress
  labels:
    app: {{ .Release.Name }}
{{ include "quarkus.labels.common" $ | indent 4 }}
  annotations:    
{{- if (.Values.prometheus | default false) }}
    prometheus.io/ingress: '{{ .Values.routing.prometheus.ingress |  default "true" }}'
    prometheus.io/ingress_path: '{{ .Values.routing.prometheus.ingress_path |  default $.Values.livenessProbe.url }}'
{{- end }}
{{ toYaml .Values.routing.ingress.annotations  | indent 4 }}
spec:
  rules:
  - host: {{ .Release.Name }}-{{ .Release.Namespace }}.{{ .Values.global.default_url | default .Values.routing.default_url }}
    http:
      paths:
      - path: {{ .Values.routing.path | default "/" }}
        pathType: Prefix
        backend:
          service:
            name: {{ include "quarkus.routing.service" $ }}
            port: 
              number: {{ .Values.routing.service.port | default .Values.service.port }}
{{ end }}
{{ end }}