{{ if .Values.routing.enabled }}
{{- if eq (include "quarkus.routing.type" $) "route" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-external-route
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
  labels:
    app: {{ .Release.Name }}
{{ include "quarkus.labels.common" $ | indent 4 }}
annotations:
spec:
  host: {{ .Release.Name }}-{{ .Release.Namespace }}.{{ .Values.global.default_url | default .Values.routing.default_url }}
  {{ if .Values.routing.path }}
  path: {{ .Values.routing.path }}
  {{ end }}
  to:
    kind: Service
    name: {{ .Release.Name }}
  port:
    targetPort: {{ .Values.service.port }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{ end }}
{{ end }}
