{{- if .Values.env_secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-env
  labels:
    app: {{ .Release.Name }}
{{ include "quarkus.labels.common" $ | indent 4 }}  
stringData:
{{- range $key,$val := .Values.env_secrets }}
  {{ $key }}: {{ tpl ($val|toString) $ | quote }}
{{- end }}
type: Opaque
{{- end }}
