{{- if .Values.db.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" $ }}-db-config
  labels:
    app: {{ template "app.fullname" $ }}
{{ include "app.labels.common" $ | indent 4 }}    
type: Opaque
stringData:
  user: {{ include "app.db.username" $ }}
  password: {{ include "app.db.password" $ }}
  database: {{ include "app.db.database" $ }}
{{- end }}
