{{- if .Values.operator.keycloak.client.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.oidc.client.secret.name" $ }}
  labels:
    app: {{ template "app.fullname" $ }}
{{ include "app.labels.common" $ | indent 4 }}    
type: Opaque
stringData:
  clientId: {{ .Values.operator.keycloak.client.spec.kcConfig.clientId | default (include "app.fullname" .) }}
  secret: {{ include "app.oidc.client.password" $ }}
{{- end }}
