{{- if .Values.env_secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-env
  labels:
    app: {{ include "app.fullname" . }}
{{ include "app.labels.common" $ | indent 4 }}  
stringData:
{{- range $key,$val := .Values.env_secrets }}
  {{ $key }}: {{ tpl ($val|toString) $ | quote }}
{{- end }}
type: Opaque
{{- end }}
