{{- if .Values.operator.keycloak.client.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.oidc.client.secret.name" $ }}
  annotations:
  {{- if .Values.operator.secretgenerator.enabled }}
  {{- if .Values.operator.keycloak.client.secret.generator.enabled }}
    secret-generator.v1.mittwald.de/autogenerate: secret
  {{- end }}
  {{- end }}
  labels:
    app: {{ template "app.fullname" $ }}
{{ include "app.labels.common" $ | indent 4 }}    
type: Opaque
stringData:
  clientId: {{ .Values.operator.keycloak.client.spec.kcConfig.clientId | default (include "app.fullname" .) }}
  {{- if not .Values.operator.keycloak.client.secret.generator.enabled }}
  secret: {{ include "app.oidc.client.password" $ }}
  {{- end }}
{{- end }}
