kind: Service
apiVersion: v1
metadata:
  name: {{ template "app.fullname" $ }}
  labels:
    app: {{ template "app.fullname" $ }}
{{ include "app.labels.common" $ | indent 4 }}    
  annotations:
    description: {{ template "app.fullname" $ }}
spec:
  selector:
    app: {{ template "app.fullname" $ }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.pod.port }}
