name: build
on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  java:
    uses: onecx/ci-common/.github/workflows/helm-build.yml@v1
    secrets: inherit
    with:
      artifact: ''    
      artifactPath: '.'